### ISSUE TITLE
Upload successive scenes doesn't work

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1#185]
**Describe the bug**
When I upload a scene_1 to a new dataset, and I upload a new scene_2 in the same dataset, I have the "SUCCESS_WITH_ERROR" error, and the scene_2 doens't appear. Is that normal ?

**To Reproduce**
Create two scenes folders. zip it with the name scene_1 and scene_2. 
Create a new dataset and import scene_1.zip then scene_2.zip.

**Expected behavior**
You should see the two scenes

**Comment by jaggerwang** [comment]
Can you give the zip package or paste the full directory structure of it.

**Comment by fanyinbo** [comment]
We have fixed the issue and are preparing to launch it soon.

**Comment by jaggerwang** [comment]
Fixed in v0.8.1.

**Comment by ClementLeBihan** [comment]
Are you sure you didn't miss something in the 0.8.1 ? The commits in dev branch about this bug hasn't been merged in the main branch. The backend folder hasn't been updated for 2 months on main branch !

**Comment by jaggerwang** [comment]
Yes, we already found this issue and repackaged v0.8.1.

**Comment by ClementLeBihan** [comment]
The source code of v0.8.1 still doesn't have last modification on UploadDataUseCase.java

**Comment by jaggerwang** [comment]
The dev branch contains some new features under development and cannot be directly merged into the main branch. v0.8.1 only includes some issue fixes. But we did miss some change on the main branch, we will fix this issue as soon as possible. Sorry!
